spring.application.name=ad-insights-backend
spring.devtools.restart.enabled=false
spring.devtools.livereload.enabled=true

# DB
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Flyway
spring.flyway.enabled=true
spring.flyway.clean-disabled=false

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Custom
app.project-site-url=http://localhost:3000

# SMTP server settings
email.name.password-reset=noreply@giraffeanalytics.co.uk
spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=nckrossi@gmail.com
spring.mail.password=ceyr egbj bepr agvc
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
